name: php
type: service
icon: php
title: PHP
hostname: php
scalable: true
labels:
- php
- php-fpm
options:
- version: '8.3'
  default: true
  eol: '2026-11-23T00:00:00+00:00'
- version: '8.2'  
  eol: '2025-12-08T00:00:00+00:00'
- version: '8.1'
  eol: '2024-11-25T00:00:00+00:00'
containers:
- name: php
  image: wodby/php
  main: true
#  resources:
#    request:
#       memory: 128
#       cpu: 100
  env:
  - name: PHP_FPM_CLEAR_ENV
    value: 'no'  
  - name: PHP_ERROR_REPORTING
    value: 'E_ALL & ~E_DEPRECATED & ~E_STRICT'
    envType: prod
  - name: PHP_DISPLAY_ERRORS
    value: 'Off'
    envType: prod
  - name: PHP_DISPLAY_STARTUP_ERRORS
    value: 'Off'
    envType: prod
  - name: PHP_TRACK_ERRORS
    value: 'Off'
    envType: prod

endpoints:
- name: fpm
  ports:
  - name: fpm
    number: 9000
    main: true
    type: tcp

build:
  dockerfile: Dockerfile
  connect: true

derivatives:
- name: php-sshd
  icon: ssh
  title: SSHD
  args: ['sudo', '/usr/sbin/sshd', '-De']
  type: ssh
  default: true
  required: false
  endpoints:
  - name: sshd
    ports:
    - name: sshd
      main: true
      number: 22
      type: tcp
  env:
  - name: SSHD_GATEWAY_PORTS
    value: clientspecified
  helm:
    values:
    - name: containerPorts
      value: {sshd: 22}
links:
- name: db
  title: DBMS
  required: true
  env:
  - name: DB_HOST
    value: '{{link.database.host}}'
  - name: DB_PORT
    value: '{{link.database.port}}'
  - name: DB_USERNAME
    value: '{{link.database.user.name}}'
  - name: DB_NAME
    value: '{{link.database.db.name}}'
  - name: DB_DATABASE
    value: '{{link.database.db.name}}'    
  - name: DB_PASSWORD
    value: '{{link.database.user.password}}'
    secret: true
  - name: DB_DRIVER
    value: '{{link.database.driver}}'  
  - name: DB_CONNECTION
    value: '{{link.database.driver}}'      
  selectors:
  - type: db
    labels:
    - mariadb
  - type: db
    labels:
    - mysql
  - type: db
    labels:
    - postgres
- name: sendmail    
  title: Mail Transfer Agent
  required: false
  env:
  - name: MSMTP_HOST
    value: '{{link.host}}'
  - name: MSMTP_PORT
    value: '{{link.port}}'
  selectors:
  - type: service
    labels: 
    - smtpd

integrations:
- name: variable
  title: Variable
  type: variable
  required: false
  multiple: true
  providers:
  - name: newrelic
    env:
    - name: PHP_NEWRELIC_LICENSE
      value: '{{integration.variables.NEWRELIC_LICENSE}}'
      secret: true
    - name: PHP_NEWRELIC_APPNAME
      value: '{{wodby_app_name}}'

helm:
  name: wodby
  source: oci://registry-1.docker.io/wodby/php-fpm
  chart: oci://registry-1.docker.io/wodby/php-fpm
  version: 0.1.2
  configurations:
  - name: php
    labels: podLabels
    annotations: podAnnotations
    env: envVars
    resources: resources
    volumes: volumes
    mounts: volumeMounts
